{% set name = "pytest-tornasync" %}
{% set version = "0.6.0.post2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d781b6d951a2e7c08843141d3ff583610b4ea86bfa847714c76edefb576bbe5d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - pytest >=3.0
    - python >=3.5
    - tornado >=5.0

test:
  imports:
    - pytest_tornasync

about:
  home: https://github.com/eukaryote/pytest-tornasync
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: py.test plugin for testing Python 3.5+ Tornado code
  dev_url: https://github.com/eukaryote/pytest-tornasync

extra:
  recipe-maintainers:
    - lincrosenbach
    - igorcandeia
    - kfasolin
    - nicoddemus
